# Generated by Django 5.0.1 on 2024-01-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
